---
- name: Install OpenLDAP and utils
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - slapd
    - ldap-utils
  tags: openldap

- name: Configure slapd
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: "slapd/no_configuration", value: "false", vtype: "select" }
    - { question: "slapd/domain", value: "{{ ldap_domain }}", vtype: "string" }
    - { question: "slapd/password1", value: "{{ ldap_admin_password }}", vtype: "password" }
    - { question: "slapd/password2", value: "{{ ldap_admin_password }}", vtype: "password" }
  become: yes
  tags: openldap

- name: Reconfigure slapd
  command: dpkg-reconfigure slapd --frontend=noninteractive
  become: yes
  when: slapd_reconfigure
  tags: openldap

- name: Ensure slapd is started and enabled
  service:
    name: slapd
    state: started
    enabled: yes
  tags: openldap

- name: Create LDAP base structure LDIF file
  copy:
    dest: /tmp/base.ldif
    content: |
      dn: ou=users,{{ ldap_base_dn }}
      objectClass: organizationalUnit
      ou: users

      dn: ou=groups,{{ ldap_base_dn }}
      objectClass: organizationalUnit
      ou: groups

      dn: cn=example_group,ou=groups,{{ ldap_base_dn }}
      objectClass: top
      objectClass: posixGroup
      gidNumber: 10000
      cn: example_group
  tags: openldap

- name: Apply LDAP base structure
  command: ldapadd -x -D "cn=admin,{{ ldap_base_dn }}" -w "{{ ldap_admin_password }}" -f /tmp/base.ldif
  tags: openldap
  notify: restart openldap
